# =====================================
# Data configuration
# =====================================

project:
  name: france-grid-stress-prediction
  timezone: UTC
  frequency: hourly

period:
  start_date: "2018-01-01"
  end_date: "2023-12-31"

electricity:
  provider: rte
  scope: france_metropolitan
  target: load
  unit: MW

weather:
  provider: open-meteo
  aggregation: population_weighted
  cities_file: data/external/agglomerations.xlsx
  variables:
    - temperature_2m
    - wind_speed_10m
    - cloud_cover
    - direct_radiation
    - diffuse_radiation
